spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop #dev settings

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: 763979244226452948404D635166546A576E5A7234753778217A25432A462D4A
      expiration: 86400000 # a day

openweathermap:
  api:
    key: ecb50481b265872817c44b68d5c142d5
  now:
    endpoint: http://api.openweathermap.org/data/2.5/weather
    city: Warsaw